version: 2.1

commands:
  env:
    description: test env variable passing
    steps:
      - run:
          name: push images
          command: |
            echo hillllll!
           

jobs:
  one:
    docker:
      - image: cimg/base:current
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Echo
          command: |
            echo << pipeline.git.branch >>
      
  two:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    parameters:
      build_artifacts:
        default: false
        type: boolean
    steps:
      - run:
          name: Echo
          command: |
            echo "A more familiar hi"
      - when:
          condition:
            and:
              - eqauls: [ true, << parameters.build_artifacts >> ]
          steps:
            - run: echo hixxx
      
  node:
    docker:
      - image: cimg/node:18.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Node version
          command: |
            node -v
        
     
workflows:
  version: 2
  one:
    when:
      or:
        - equal: [ master, << pipeline.git.branch >> ]
        - equal: [xcircleci-project-setup, << pipeline.git.branch >>]
    jobs:
      - one
  twowf:
    jobs:
      - two
