version: 2.1
jobs:
  one:
    docker:
      - image: cimg/base
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Echo
          command: |
            echo << pipeline.git.branch >>
      
  two:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Echo
          command: |
            echo "A more familiar hi"
      
  node:
    docker:
      - image: cimg/node:18.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Node version
          command: |
            node -v
        
     
workflows:
  version: 2
  one:
    when:
      condition:
        and:
          equal: [master, << pipeline.git.branch >> ]
    jobs:
      - one
  two:
    jobs:
      - two
      - node:
          requires:
            - two
