version: 2
jobs:
  one:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
        name: Echo
        command: |
          echo "A first hello"
      
  two:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
        name: Echo
        command: |
          echo "A more familiar hi"
      
  node:
    docker:
      - image: cimg/node:18.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
        name: Node version
        command: |
          node -v
        
     
workflows:
  one:
    jobs:
      - one
  two:
    jobs:
      - two
      - node
