version: 2.1

commands:
  push:
    description: test env variable passing
    steps:
      - run:
          name: push images
          command: |
            echo "BUILD=$BUILD_ARTIFACTS"
           

jobs:
  one:
    docker:
      - image: cimg/base:current
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Echo
          command: |
            echo << pipeline.git.branch >>
      
  two:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    parameters:
      build_artifacts:
        default: false
        type: boolean
    steps:
      - run:
          name: Echo
          command: |
            BUILD_ARTIFACTS=''
            if [ << parameters.build_artifacts >> ];then
              echo "export BUILD_ARTIFACTS=YES" >> $BASH_ENV
            fi
      - when:
          condition:
            and:
              - << parameters.build_artifacts >> 
          steps:
            - push 
      
  node:
    docker:
      - image: cimg/node:18.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Node version
          command: |
            node -v
        
     
workflows:
  version: 2
  one:
    when:
      or:
        - equal: [ master, << pipeline.git.branch >> ]
        - equal: [xcircleci-project-setup, << pipeline.git.branch >>]
    jobs:
      - one
  twowf:
    jobs:
      - two:
            build_artifacts: true
